server:
  port: 8000 

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

info:
  app:
    name: Authorization Server

endpoints:
  shutdown:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true

spring:
  security:
    oauth2:
      client: 
        registration:
          google:
            client-id: 901419559875-bmfve16j9gg88tvejmmnjeuqij2et7ga.apps.googleusercontent.com 
            client-secret: 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
